apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-app1-ingress
  namespace: nginx-app1
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`svc.lab.ln`) || Host(`svc`) # default url is app1
      kind: Rule
      services:
        - name: nginx-app1-service
          port: 80
  tls: {}