apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: app1-ingress
  namespace: app1
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`app1.svc.lab.ln`) || Host(`app1.svc`)
      kind: Rule
      services:
        - name: app1-service
          port: 80
    - match: Host(`svc.lab.ln`) && PathPrefix(`/app1`)
      kind: Rule
      middlewares:
        - name: app1-strip-prefix
      services:
        - name: app1-service
          port: 80
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: app1-strip-prefix
  namespace: app1
spec:
  stripPrefix:
    prefixes:
      - /app1
