apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whisker-ingress
  namespace: calico-system
spec:
  entryPoints:
    - https-admin
  routes:
    - match: Host(`whisker.k8s.lab.ln`)
      kind: Rule
      services:
        - name: whisker
          port: 8081
  tls:
    store:
      name: admin-tls-store
