apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whisker-ingress
  namespace: calico-system
spec:
  entryPoints:
    - https-admin
  routes:
    - match: Host(`whisker.k8s.lab.ln`)
      kind: Rule
      services:
        - name: whisker
          port: 8081
  tls: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-access
  namespace: calico-system
spec:
  podSelector:
    matchLabels:
      k8s-app: whisker 
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 8081
