apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: simple-app-ingress
  namespace: simple-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`app.svc.lab.ln`)
      kind: Rule
      services:
        - name: simple-app-service
          port: 8080
  tls: {}
