apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: app2-ingress
  namespace: app2
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`app2.svc.lab.ln`) || Host(`app2.svc`)
      kind: Rule
      services:
        - name: app2-service
          port: 80
    - match: Host(`svc.lab.ln`) && PathPrefix(`/app2`)
      kind: Rule
      middlewares:
        - name: app2-strip-prefix
      services:
        - name: app2-service
          port: 80
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: app2-strip-prefix
  namespace: app2
spec:
  stripPrefix:
    prefixes:
      - /app2
